/*
GuitarChords component is rendered
on the ChordsVisualizerPage to show a guitar chart with the selected chord position

Objetives that need implementation:

- The component is receiving the chord from
@tombatossals/react-chords/lib/Chord' 
(Installation of the library: npm install @tombatossals/react-chords)
and the idea will be to use this library for chord-matching(using filter())
to render the chord generated by the selected (key) KeyCreator & (suffix) ChordSuffixCreator

- For that the GuitarChords should receive the props:
sended by the parent: ChordsVisualizerPage
<GuitarChords selectedKeyValue= {(selectedKeyValue)} selectedSuffix={(selectedSuffix)} />
using them:
const GuitarChords = (selectedKeyValue, selectedSuffix)
to match their values with react-chords library to render 
the actual Chord that has been selected on the ChordsVisualizerPage.

*/



//import { useState } from 'react';

//import guitar from '../chords-db/lib/guitar';


import Chord from '@tombatossals/react-chords/lib/Chord'


const GuitarChords = (selectedKeyValue, selectedSuffix) => {
    if (!selectedKeyValue && !selectedSuffix) {
        return null;
  }
  
 
    
    console.log(selectedKeyValue);
    console.log(selectedSuffix);
      // Get the chord data from the guitar.js file
      //const chordData = guitar.chords[selectedKeyValue]?.find(
      //  chord => chord.suffix === selectedSuffix);
    // console.log(chordData);
  // https://tombatossals.github.io/react-chords/ukulele/A/sus2
  
 // const url = `https://tombatossals.github.io/react-chords/ukulele/${selectedKeyValue}/${selectedSuffix}`;


  
    const chord = {
      frets: [1, 3, 3, 2, 1, 1],
      fingers: [1, 3, 4, 2, 1, 1],
      barres: [1],
      capo: false,
  }
    
      const instrument = {
        strings: 6,
        fretsOnChord: 4,
          name: 'Guitar',
         
        tunings: {
            standard: ['E', 'A', 'D', 'G', 'B', 'E'],
        },
    };
    
    
      // Return the chord data if found, otherwise return null
      const lite = false;
    
      return (
        <div className="Chord_design">
            <h1>GUITAR</h1>
          
          <Chord chord={chord} instrument={instrument} lite={lite} />
          
           
        </div>
    );
};

export default GuitarChords;
